/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutBoardIndexRouteImport } from './routes/_layout/board/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as LayoutShareUuidRouteImport } from './routes/_layout/share/$uuid'
import { Route as LayoutBoardNewRouteImport } from './routes/_layout/board/new'
import { Route as LayoutBoardLiveApiRouteImport } from './routes/_layout/board/live-api'
import { Route as LayoutBoardListRouteImport } from './routes/_layout/board/list'
import { Route as LayoutBoardUuidRouteImport } from './routes/_layout/board/$uuid'
import { Route as LayoutBoardUuidForkRouteImport } from './routes/_layout/board/$uuid_.fork'
import { Route as LayoutBoardUuidEditRouteImport } from './routes/_layout/board/$uuid_.edit'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutBoardIndexRoute = LayoutBoardIndexRouteImport.update({
  id: '/board/',
  path: '/board/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutShareUuidRoute = LayoutShareUuidRouteImport.update({
  id: '/share/$uuid',
  path: '/share/$uuid',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBoardNewRoute = LayoutBoardNewRouteImport.update({
  id: '/board/new',
  path: '/board/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBoardLiveApiRoute = LayoutBoardLiveApiRouteImport.update({
  id: '/board/live-api',
  path: '/board/live-api',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBoardListRoute = LayoutBoardListRouteImport.update({
  id: '/board/list',
  path: '/board/list',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBoardUuidRoute = LayoutBoardUuidRouteImport.update({
  id: '/board/$uuid',
  path: '/board/$uuid',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBoardUuidForkRoute = LayoutBoardUuidForkRouteImport.update({
  id: '/board/$uuid_/fork',
  path: '/board/$uuid/fork',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBoardUuidEditRoute = LayoutBoardUuidEditRouteImport.update({
  id: '/board/$uuid_/edit',
  path: '/board/$uuid/edit',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board/$uuid': typeof LayoutBoardUuidRoute
  '/board/list': typeof LayoutBoardListRoute
  '/board/live-api': typeof LayoutBoardLiveApiRoute
  '/board/new': typeof LayoutBoardNewRoute
  '/share/$uuid': typeof LayoutShareUuidRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/board/': typeof LayoutBoardIndexRoute
  '/board/$uuid/edit': typeof LayoutBoardUuidEditRoute
  '/board/$uuid/fork': typeof LayoutBoardUuidForkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board/$uuid': typeof LayoutBoardUuidRoute
  '/board/list': typeof LayoutBoardListRoute
  '/board/live-api': typeof LayoutBoardLiveApiRoute
  '/board/new': typeof LayoutBoardNewRoute
  '/share/$uuid': typeof LayoutShareUuidRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/board': typeof LayoutBoardIndexRoute
  '/board/$uuid/edit': typeof LayoutBoardUuidEditRoute
  '/board/$uuid/fork': typeof LayoutBoardUuidForkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/board/$uuid': typeof LayoutBoardUuidRoute
  '/_layout/board/list': typeof LayoutBoardListRoute
  '/_layout/board/live-api': typeof LayoutBoardLiveApiRoute
  '/_layout/board/new': typeof LayoutBoardNewRoute
  '/_layout/share/$uuid': typeof LayoutShareUuidRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_layout/board/': typeof LayoutBoardIndexRoute
  '/_layout/board/$uuid_/edit': typeof LayoutBoardUuidEditRoute
  '/_layout/board/$uuid_/fork': typeof LayoutBoardUuidForkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board/$uuid'
    | '/board/list'
    | '/board/live-api'
    | '/board/new'
    | '/share/$uuid'
    | '/api/trpc/$'
    | '/board/'
    | '/board/$uuid/edit'
    | '/board/$uuid/fork'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board/$uuid'
    | '/board/list'
    | '/board/live-api'
    | '/board/new'
    | '/share/$uuid'
    | '/api/trpc/$'
    | '/board'
    | '/board/$uuid/edit'
    | '/board/$uuid/fork'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/board/$uuid'
    | '/_layout/board/list'
    | '/_layout/board/live-api'
    | '/_layout/board/new'
    | '/_layout/share/$uuid'
    | '/api/trpc/$'
    | '/_layout/board/'
    | '/_layout/board/$uuid_/edit'
    | '/_layout/board/$uuid_/fork'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/board/': {
      id: '/_layout/board/'
      path: '/board'
      fullPath: '/board/'
      preLoaderRoute: typeof LayoutBoardIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/share/$uuid': {
      id: '/_layout/share/$uuid'
      path: '/share/$uuid'
      fullPath: '/share/$uuid'
      preLoaderRoute: typeof LayoutShareUuidRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/board/new': {
      id: '/_layout/board/new'
      path: '/board/new'
      fullPath: '/board/new'
      preLoaderRoute: typeof LayoutBoardNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/board/live-api': {
      id: '/_layout/board/live-api'
      path: '/board/live-api'
      fullPath: '/board/live-api'
      preLoaderRoute: typeof LayoutBoardLiveApiRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/board/list': {
      id: '/_layout/board/list'
      path: '/board/list'
      fullPath: '/board/list'
      preLoaderRoute: typeof LayoutBoardListRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/board/$uuid': {
      id: '/_layout/board/$uuid'
      path: '/board/$uuid'
      fullPath: '/board/$uuid'
      preLoaderRoute: typeof LayoutBoardUuidRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/board/$uuid_/fork': {
      id: '/_layout/board/$uuid_/fork'
      path: '/board/$uuid/fork'
      fullPath: '/board/$uuid/fork'
      preLoaderRoute: typeof LayoutBoardUuidForkRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/board/$uuid_/edit': {
      id: '/_layout/board/$uuid_/edit'
      path: '/board/$uuid/edit'
      fullPath: '/board/$uuid/edit'
      preLoaderRoute: typeof LayoutBoardUuidEditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBoardUuidRoute: typeof LayoutBoardUuidRoute
  LayoutBoardListRoute: typeof LayoutBoardListRoute
  LayoutBoardLiveApiRoute: typeof LayoutBoardLiveApiRoute
  LayoutBoardNewRoute: typeof LayoutBoardNewRoute
  LayoutShareUuidRoute: typeof LayoutShareUuidRoute
  LayoutBoardIndexRoute: typeof LayoutBoardIndexRoute
  LayoutBoardUuidEditRoute: typeof LayoutBoardUuidEditRoute
  LayoutBoardUuidForkRoute: typeof LayoutBoardUuidForkRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBoardUuidRoute: LayoutBoardUuidRoute,
  LayoutBoardListRoute: LayoutBoardListRoute,
  LayoutBoardLiveApiRoute: LayoutBoardLiveApiRoute,
  LayoutBoardNewRoute: LayoutBoardNewRoute,
  LayoutShareUuidRoute: LayoutShareUuidRoute,
  LayoutBoardIndexRoute: LayoutBoardIndexRoute,
  LayoutBoardUuidEditRoute: LayoutBoardUuidEditRoute,
  LayoutBoardUuidForkRoute: LayoutBoardUuidForkRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
